#!/bin/bash

if [ "$1" ]; then
  ## determine path to app for includes
  APP_EXECUTION_PATH="$0"
  APP_EXECUTION_ROOT="$(cd "$(dirname "$APP_EXECUTION_PATH")"; pwd)"
  DATA_DIRECTORY="$APP_EXECUTION_ROOT/raw"

  ## drop database
  mongo "$1" --eval "db.dropDatabase()"

  ## import collections from json files
  for filename in "$DATA_DIRECTORY"/*.json; do
    data_filename="$(basename "$filename")"
    data_collection_name="${data_filename%.*}"
    mongoimport --db "$1" --collection "$data_collection_name" --type json --file "$filename" --jsonArray
  done

  ## add indices
  for filename in "$DATA_DIRECTORY"/*.index; do
    data_filename="$(basename "$filename")"
    data_collection_name="${data_filename%.*}"
    while read fieldname; do
      mongo "$1" --eval "db.$data_collection_name.ensureIndex({$fieldname: 1},{unique: true})"
    done < "$filename"
  done
else
  printf "NO DB SPECIFIED!!! Please execute this script with the name of the db you would like to seed as the first argument\n"
fi
